
<!-- sub nav bar -->
<div  style='width: 200px;float:left'>

<div>
<div>
<h3>用户账户</h3>
</div>
<ul>
	<li class="active"><a href="/my/account/settings">Account
	Settings</a></li>
	<li><a href="https://www.zazzle.com/my/orders/history">Order History</a></li>
	<li><a href="http://www.zazzle.com/my/account/addressbook">Address Book</a></li>

	<li><a href="https://www.zazzle.com/my/account/sharing">Sharing</a></li>

	<li><a href="https://www.zazzle.com/my/earnings/paymentsettings">Payment
	Settings</a></li>

</ul>

</div>
</div>
