
<!-- sub nav bar -->

<div class="categoryList">
<div class="categoryTitleShell">
<h3>用户账户</h3>
</div>
<ul class="categoryListShadow">
	<li class="active"><a href="https://www.zazzle.com/my/account/settings">Account
	Settings</a></li>
	<li><a href="https://www.zazzle.com/my/orders/history">Order History</a></li>
	<li><a href="http://www.zazzle.com/my/account/addressbook">Address Book</a></li>

	<li><a href="https://www.zazzle.com/my/account/sharing">Sharing</a></li>

	<li><a href="https://www.zazzle.com/my/earnings/paymentsettings">Payment
	Settings</a></li>

</ul>

</div>
