<div id="mainShellCentered">
<div id="pageTopCap"><!----></div>
<div class="mantle" id="pageMantle"><!----></div>
<div id="pageHeader">
<?=$this->partial ( '/partials/_head.phtml', array ('title' => 'mail', 'subject' => 'view partials' ) );?>
<div class="mantle" id="pageHeaderMantle"><!----></div>
<div id="pageHeaderContent"><!----></div>
<div id="pageHeaderControls">
<div class="controls clearfix"><!----></div>
</div>
</div>
<div class="clearfix" id="main">
<div class="clearfix navPane" id="group_1">
<?=$this->partial ( '/partials/_leftNav.phtml', array ('title' => 'mail', 'subject' => 'view partials' ) );?>
</div>
<div class="clearfix contentPane" id="group_2">

<div class="mantle" id="contentPaneMantle"><!----></div>
<div class="controls clearfix"><!----></div>
</div>
</div>
</div>
