<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

$this->layout()->userForm = $this->action('index', 'lgn');
?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php
$this->headTitle()->setPrefix('Ink Map');
echo $this->headTitle();
if ($this->dojo()->isEnabled()){
	$this->dojo()->setLocalPath('/scripts/dojo/dojo/dojo.js')
	->addStyleSheetModule('dijit.themes.tundra');
	echo $this->dojo();
}
echo $this->headScript();
$this->headLink()->appendStylesheet('/styles/layout.css');
$this->headLink()->appendStylesheet('/styles/default/footer.css');
$this->headLink()->appendStylesheet('/styles/default/head.css');
echo $this->headLink();
?>
<script type="text/javascript"
	src="http://www.zazzle.com/bld/z.2/js/library/Zazzle.js?r=trunk.83214"></script>
</head>

<body class='tundra'>
<!---------------------------------------------------------------this is header-->
<div class="clearfix" id="header">
<div id="crossSiteShell">
<div id="crossSiteContent">
<div id="siteLinksContent"></div>
<div id="utilityLinksContent">
<div class="utilitiesShell" id="page-consoleLinks2"><?php
echo $this->layout()->userForm;
?></div>
</div>
<div class="skinningLeftOutside"><!----></div>
<div class="skinningRightOutside"><!----></div>
</div>
</div>
<div class="breadcrumb"><!----></div>
<div id="headerSearchBar"></div>
</div>
<!---------------------------------------------------------------this is main content-->
<div id="mainShell"><?php echo $this->layout()->content?></div>
<!---------------------------------------------------------------this is footer-->
<div id="footer">
<div id="footerContent">
<div class="footerMain">
<p><em>Powered by Sean Panda</em></p>
</div>
</div>
</div>
</body>
</html>
