<div id="utilityLinks">
<?php
if ($this->auth == true) {
	?>	

<strong>欢迎!&nbsp;<?php
	echo $this->user_name;
	?>
</strong> <span class="welcomeSignout">( <a id="page_logoutLink"
	href="/lgn/signout">注销..</a>) </span> &nbsp;|&nbsp; <span
	class="utilityLinksCell">
<?php
} else {
	?>
	<strong>有InkMap账号?&nbsp;</strong>
	<a href="/lgn/signin" id="page-loginLink" target="_top">登录</a>
	&nbsp;|&nbsp;
<?php
}
?>
<a target="_top" id="page-headerLinkCart"
	href="http://www.zazzle.com/co/cart">购物车 <span class="cartItems"></span></a>
&nbsp;|&nbsp;<a target="_top" id="page-headerLinkMyAccount"
	href="/my/account/settings">我的账户</a> &nbsp;|&nbsp;<a target="helpPopup"
	id="page-headerLinkHelp" href="javascript://">帮助</a><a
	class="headerToggler" id="zBar-contract" href="javascript://"></a> </span>
</div>