<div id="utilityLinks"><strong>Welcommmmm <a
	href="http://www.zazzle.com/mathematix">mathematix</a>!</strong> <span
	class="welcomeSignout">(<a id="page_logoutLink"
	href="/lgn/signout">Not
you</a>?)</span> &nbsp;|&nbsp;<span class="utilityLinksCell"><a
	target="_top" id="page-headerLinkCart"
	href="http://www.zazzle.com/co/cart">Cart <span class="cartItems">(1)</span></a>
&nbsp;|&nbsp;<a target="_top" id="page-headerLinkMyAccount"
	href="http://www.zazzle.com/my/home">My Account</a> &nbsp;|&nbsp;<a
	target="helpPopup" id="page-headerLinkHelp" href="javascript://">Help</a><a
	class="headerToggler" id="zBar-contract" href="javascript://"></a></span>
</div>