<script type="text/javascript">

$(document).ready(function() {
	passwordBind($('#password1'));
	passwordBind($('#password2'));
	confirmBind($('#password3'),$('#password2'));
	submitBind($('#submit'));
});
function passwordBind(obj){
	obj.bind('focus', function(){
		resetError($(this));
		var passValue = $(this).val();  
		if(passValue.length<6 && passValue.length>0){
			showTooltip($(this),"长度太短鸟～");
		}
	});
	obj.bind('keyup', function(){
		var passValue = $(this).val();  
		if(passValue.length>0 && passValue.length<=5){
			showTooltip($(this),"长度太短鸟～");
		}
		else{
			hideTooltip();
		}
	});
	obj.bind('blur',function(){
		var passValue = $(this).val();  
		if(passValue.length<=5 && passValue.length>0){
			setError($(this));
		}
		hideTooltip();
	});
};

function confirmBind(obj,passObj){
	obj.bind('focus', function(){
		resetError($(this));
		var confirmPassValue = $(this).val();  
		var passValue = passObj.val();
		if(passValue!=confirmPassValue && confirmPassValue.length>0){
			showTooltip($(this),"两次密码不相等鸟～");
		}
	});
	obj.bind('keyup', function(){
			hideTooltip();
	});
	obj.bind('blur',function(){
		var confirmPassValue = $(this).val();  
		var passValue = passObj.val();  
		if(passValue!=confirmPassValue){
			setError($(this));
		}
		hideTooltip();
	});
};

function submitBind(obj){
	obj.bind('click',function(){
		var password1 = $('#password1').val(); 
		var password2 = $('#password2').val();  
		var password3 = $('#password3').val();   
		if(password1.length<6 || password2.length<6 || password2!=password3){
			if(password1.length<6){
				$('#password1').focus();}
			else if(password2.length<6){
				$('#password2').focus();}
			else if (password2!=password3){
				$('#password3').focus();}
			return false;
		}
		else{
			$('#password').submit();
		}	
	});
};

function setError(obj) {
	obj.attr('class','error');
};
function resetError(obj) {
	obj.attr('class','');
};
function showTooltip(obj,message){
	var a = obj.offset();
	var top=a.top-10;
	var left=a.left+obj.width()+20;
	$("#tipContent").html(message);
	$("#errorTooltip").attr("style","top: "+top+"px; left: "+left+"px; opacity: 1;");
};
function hideTooltip(){
	$("#errorTooltip").attr('style','');
};

</script>
<style type="text/css">
.formRow {
	height: 40px;
}

.formLabel {
	color: black;
	display: inline-block;
	width: 80px
}
</style>

<!-- end of head -->
<div id="mainShellCentered">
<div id="pageTopCap"><!----></div>
<div class="mantle" id="pageMantle"><!----></div>
<div id="pageHeader">
<?=$this->partial ( '/partials/_head.phtml', array ('title' => 'account', 'subject' => 'view partials' ) );?>
<div class="mantle" id="pageHeaderMantle"><!----></div>
<div id="pageHeaderContent"><!----></div>
<div id="pageHeaderControls">
<div class="controls clearfix"><!----></div>
</div>
</div>
<div class="clearfix" id="main">
<div class="clearfix navPane" id="group" style='width: 200px'>
<?=$this->partial ( '/partials/_leftNav.phtml', array ('title' => 'account', 'subject' => 'view partials' ) );?>
</div>
<div class="clearfix contentPane" id="group_2">

<?=$this->partial ( '/partials/_accountTab.phtml', array ('title' => 'password', 'subject' => 'view partials' ) );?>

<?php
echo $this->passForm;
?>
<?php

if ($this->changeMessage != "") {
	?>
<div id='changeMessage'><?php
	echo $this->changeMessage?></div>
<?php
}
?>
<div class="mantle" id="contentPaneMantle"><!----></div>
<div class="controls clearfix"><!----></div>
</div>
</div>
</div>
<!--render tooltip -->
<?=$this->partial ( '/partials/_toolTip.phtml');?>
