

<div id="mainShellCentered">
<div id="pageTopCap"><!----></div>
<div class="mantle" id="pageMantle"><!----></div>
<div id="pageHeader">
<?=$this->partial ( '/partials/_head.phtml', array ('title' => 'account', 'subject' => 'view partials' ) );?>
<div class="mantle" id="pageHeaderMantle"><!----></div>
<div id="pageHeaderContent"><!----></div>
<div id="pageHeaderControls">
<div class="controls clearfix"><!----></div>
</div>
</div>
<div class="clearfix" id="main">
<div class="clearfix navPane" id="group" style='width: 200px'>
<?=$this->partial ( '/partials/_leftNav.phtml', array ('title' => 'account', 'subject' => 'view partials' ) );?>
</div>
<div class="clearfix contentPane" id="group_2">

<?=$this->partial ( '/partials/_accountTab.phtml', array ('title' => 'password', 'subject' => 'view partials' ) );?>


<div class="mantle" id="contentPaneMantle"><!----></div>
<div class="controls clearfix"><!----></div>
</div>
</div>
</div>