<?php
echo '<?xml version="1.0" encoding="UTF-8" ?>';
echo $this->doctype();

$this->layout()->userForm = $this->action('index', 'lgn');
?>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<?php
$this->headTitle()->setPrefix('Ink Map');
echo $this->headTitle();
if ($this->dojo()->isEnabled()){
	$this->dojo()->setLocalPath('/scripts/dojo/dojo/dojo.js')
	->addStyleSheetModule('dijit.themes.tundra');
	echo $this->dojo();
}
//$this->headScript()->setScript('/scripts/jquery.js');
//$this->headScript()->appendScript('/scripts/jquery.Jcrop.js');
echo $this->headScript();
$this->headLink()->appendStylesheet('/styles/jquery.Jcrop.css');
echo $this->headLink();
?>
<link rel="stylesheet" type="text/css" href="https://www.zazzle.com/css/default.zss/r-1112b1a123efb1848b078527bb19afe5.css?lang=Default&zcur=USD&oh=www.zazzle.com" />
<link rel="stylesheet" type="text/css" href="https://www.zazzle.com/css/skins/default.zss/r-1912c402af35431367b05335858d558e.css?lang=Default&zcur=USD&oh=www.zazzle.com" />	
<link rel="Shortcut Icon" href="/images/favicon.ico">
<script type="text/javascript" src="/scripts/jquery-1.4.1.js"></script>
</head>

<body class='tundra'>
<!---------------------------------------------------------------this is header-->
<div class="clearfix" id="header">
<div id="crossSiteShell">
<div id="crossSiteContent">
<div id="siteLinksContent"></div>
<div id="utilityLinksContent">
<div class="utilitiesShell" id="page-consoleLinks2"><?php
echo $this->layout()->userForm;
?></div>
</div>
<div class="skinningLeftOutside"><!----></div>
<div class="skinningRightOutside"><!----></div>
</div>
</div>
<div class="breadcrumb"><!----></div>
<div id="headerSearchBar"></div>
</div>
<!---------------------------------------------------------------this is main content-->
<div id="mainShell"><?php echo $this->layout()->content?></div>
<!---------------------------------------------------------------this is footer-->
<div id="footer">
<div id="footerContent">
<div class="footerMain">
<p><em>Powered by Sean Panda</em></p>
          
</div>
</div>
</div>
</body>
</html>
